# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  MainApp_config = debug

else ifeq ($(config),release)
  MainApp_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := MainApp

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

MainApp:
ifneq (,$(MainApp_config))
	@echo "==== Building MainApp ($(MainApp_config)) ===="
	@${MAKE} --no-print-directory -C . -f MainApp.make config=$(MainApp_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f MainApp.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   MainApp"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"